---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: check-yaml
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=750"]
