---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: check-yaml
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=750"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.3
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v4.1.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/gitguardian/gg-shield
    rev: v1.4.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
